#!/usr/bin/env node

var parser = require("nomnom")
var Promise = require('bluebird')
var glob = require("glob")
var findpkgs = require("../lib/composer-findpackages.js")
var _ = require("underscore")

parser.command("scan")
  .option("repo", {
    help: "repository URI"
  })
  .option("subdir", {
    help: "subdirectory in repository"
  })
  .callback(function(opts) {
    return findpkgs(".", ['test/', 'tests/', 'vendor/'])
    .then(function (source_units) {
      if (!source_units || source_units.length < 1) {
        console.log(JSON.stringify([], null, 2));
        return;
      }

      // convert from composer-findpkgs format to source unit
      var srcunits = source_units.map(function(pkg) {
        return {
          'Name': pkg.name,
          'Type': "ComposerPackage",
          'Dir': pkg.dir,
          'Version': pkg.version,
          'Files': pkg.files,
          'Dependencies': pkg.dependencies,
          'Data': pkg,
          'Ops': {depresolve: null, graph: null},
          'Config': {}
        };
      })
      
      console.log(JSON.stringify(srcunits, null, 2));
    })
    .catch(function (err) {
      console.error("Error scanning composer packages: " + err)
      process.exit(1)
    })
  })
  .help("scan for Composer packages");

parser.parse();
